### ISSUE TITLE
Feature Suggestion: In-stream ability to update "PROMPT" parameter

### ISSUE THREAD

**Issue by zatricky** [gpoitch/term-sheets#3]
First off, thank you for creating this. It's a wonderful tool for documentation!!!

I noticed the included "create react app" demo includes a `cd` command - but then the prompt still shows `~$` afterward. There doesn't yet seem to be a way to update that, hence this issue. :)

**Comment by gpoitch** [comment]
Great suggestion and a key feature I forgot.  PR coming up.
