### ISSUE TITLE
IE and Edge not working

### ISSUE THREAD

**Issue by hacheraw** [gpoitch/term-sheets#7]
Any plans on supporting them?

*IE:* not showing any text...
*Edge:* not showing any text...
~~*Safari:* terminal completely black...~~

Thank you!

**Comment by gpoitch** [comment]
The app isn't working or an exported sheet?
Which versions? Screenshots or any more info? 

Safari should definitely work, as that is what this was created with.

**Comment by hacheraw** [comment]
Edge 42.17134.1.0 @ Windows 10
![Edge 42.17134.1.0 @ Windows 10](https://user-images.githubusercontent.com/10481749/45847573-5d341700-bd23-11e8-96cd-400b54cde32b.png)
--
IE 11.285 @ Windows 10
![IE 11.285 @ Windows 10](https://user-images.githubusercontent.com/10481749/45847836-417d4080-bd24-11e8-8607-fcbe295a2008.png)
--

Actually I haven't tested it on Safari, sorry. Just tested it on [this site](https://www.browserling.com/browse/win/7/opera/52/https%3A%2F%2Fgpoitch.github.io%2Fterm-sheets%2F)
So it may be wrong, sorry!

By the way, at this moment the app is having connection issues in my IE (that's why the second screenshot is from an exported sheet) and on Safati at browserling.com but this is justa a coincidence.

**Comment by gpoitch** [comment]
Great, thanks for the info.  I'd be interested in getting the app working in Edge.  I don't plan to support the app in IE but would be nice to have at least the exported sheets working there.

**Comment by gpoitch** [comment]
It appears the terminal appears blank in Edge because it can't animate width/height to auto, which is used to achieve the typing effect.  Haven't found a workaround yet.
